# Generated by Django 4.2 on 2024-07-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('director', models.CharField(max_length=50)),
                ('year_realease', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
